### PR TITLE
 [21346] Fix generation for new kind of constants

### LINKED ISSUE #150: idl-parser 3.0.0: idl parse error observed when idl contains a struct which references an array typedef
The below mentioned idl file parsing fails with error (**idl-parser 3.0.0** is used) :

IDL file:
> module module1
{
   enum mod1_enum_val
   {
      value1, //1
      value2 //2
   }; //mod1_enum_val
}; //module1
const module1::mod1_enum_val enum1 = module1::mod1_enum_val::value1;
typedef string StringU;
typedef int32 IntArray[23];
struct SampleStruct
{
   StringU stringU;
   IntArray ArrayInt32;
}; //SampleStruct

Error:

> Processing the file /tmp/IdlParseError.idl...
/tmp/IdlParseError.idl:11:26: error: Error evaluating array dimension: ;enum1=module1::mod1_enum_val::value1;enum1=module1::mod1_enum_val::value1;(23) | 0
/tmp/IdlParseError.idl:15:3: error: 'IntArray' was not defined previously

In the above idl file, there is a struct which tries to declare an int array as typedef. One observation is that when the enum declaration (**const module1::mod1_enum_val enum1 = module1::mod1_enum_val::value1;**) is removed/commented, the parsing works fine.

Below command is used :

> \<Path to java11 exe\> -jar \<path to fastddsgen.jar\> -replace -ppDisable -d \<path to folder where files should be generated\> \<path to IdlParseError.idl file\>

For example:

> "/home/user/java11/jre/bin/java" -jar "/home/user/fastddsgen.jar" -replace -ppDisable -d "/home/user/SampleFolder" "/home/user/IdlParseError.idl"

### PR DESCRIPTION
**Pull request by richiware**
## Description

Fixes #150.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- *N/A* Any new/modified methods have been properly documented.
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

File: src/main/java/com/eprosima/idl/parser/tree/ConstDeclaration.java [hunk 1]
```diff
@@ -21,12 +21,21 @@
...
+        TypeCode typecode, 
+        String value,
+        String evaluated_value,
+        Token token)
     {
         super(scopeFile, isInScope, scope, name, token);
 
         m_typecode = typecode;
         m_value = value;
+        evaluated_value_ =evaluated_value;
```
Comment (EduPonz) [inline src/main/java/com/eprosima/idl/parser/tree/ConstDeclaration.java:38]:
```suggestion
        evaluated_value_ = evaluated_value;
```

**Review by EduPonz — CHANGES_REQUESTED** [review]

**Review by EduPonz — APPROVED** [review]
